package com.su.communityconnect

const val SIGN_IN_SCREEN = "SignInScreen"
const val SIGN_UP_SCREEN = "SignUpScreen"
const val SPLASH_SCREEN = "SplashScreen"
const val HOME_SCREEN = "HomeScreen"
const val FORGOT_PASSWORD_SCREEN = "ForgotPasswordScreen"
const val CATEGORY_SCREEN = "CategoryScreen"
const val FAVOURITE_SCREEN = "FavouriteScreen"
const val EVENT_SCREEN = "EventScreen"
const val USER_PROFILE_SCREEN = "UserProfileScreen"
const val LOCATION_SELECTION_SCREEN = "LocationSelectionScreen"
const val EVENT_DETAIL_SCREEN = "EventDetailScreen"
const val EVENT_TICKET_BOOKING_SCREEN = "EventTicketBookingScreen"
const val EVENT_TICKET_SCREEN = "EventTicketScreen"
const val MAP_SCREEN = "MapScreen"
const val MY_TICKETS_SCREEN = "MyTicketsScreen"
const val MY_EVENTS_SCREEN = "MyEventsScreen"
